language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - flake8 ./src
  - python ./src/manage.py validate_templates
  - python ./src/manage.py check
  - python ./src/manage.py makemigrations --check --dry-run
  - pip check
  - pytest ./src/tests -s
os:
  - osx